//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryEasyUI_Tree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNode
    {
        public TreeNode()
        {
            this.TreeNode1 = new HashSet<TreeNode>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<TreeNode> TreeNode1 { get; set; }
        public virtual TreeNode TreeNode2 { get; set; }
    }
}
